<?php

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['id' => 1, 'name' => 'Afghanistan'],
            ['id' => 2, 'name' => 'Albania'],
            ['id' => 3, 'name' => 'Algeria'],
            ['id' => 4, 'name' => 'Andorra'],
            ['id' => 5, 'name' => 'Angola'],
            ['id' => 6, 'name' => 'Anguilla'],
            ['id' => 7, 'name' => 'Antigua & Barbuda'],
            ['id' => 8, 'name' => 'Argentina'],
            ['id' => 9, 'name' => 'Armenia'],
            ['id' => 10, 'name' => 'Australia'],
            ['id' => 11, 'name' => 'Austria'],
            ['id' => 12, 'name' => 'Azerbaijan'],
            ['id' => 13, 'name' => 'Bahamas'],
            ['id' => 14, 'name' => 'Bahrain'],
            ['id' => 15, 'name' => 'Bangladesh'],
            ['id' => 16, 'name' => 'Barbados'],
            ['id' => 17, 'name' => 'Belarus'],
            ['id' => 18, 'name' => 'Belgium'],
            ['id' => 19, 'name' => 'Belize'],
            ['id' => 20, 'name' => 'Benin'],
            ['id' => 21, 'name' => 'Bermuda'],
            ['id' => 22, 'name' => 'Bhutan'],
            ['id' => 23, 'name' => 'Bolivia'],
            ['id' => 24, 'name' => 'Bosnia & Herzegovina'],
            ['id' => 25, 'name' => 'Botswana'],
            ['id' => 26, 'name' => 'Brazil'],
            ['id' => 27, 'name' => 'Brunei Darussalam'],
            ['id' => 28, 'name' => 'Bulgaria'],
            ['id' => 29, 'name' => 'Burkina Faso'],
            ['id' => 30, 'name' => 'Burundi'],
            ['id' => 31, 'name' => 'Cambodia'],
            ['id' => 32, 'name' => 'Cameroon'],
            ['id' => 33, 'name' => 'Canada'],
            ['id' => 34, 'name' => 'Cape Verde'],
            ['id' => 35, 'name' => 'Cayman Islands'],
            ['id' => 36, 'name' => 'Central African Republic'],
            ['id' => 37, 'name' => 'Chad'],
            ['id' => 38, 'name' => 'Chile'],
            ['id' => 39, 'name' => 'China'],
            ['id' => 40, 'name' => 'Colombia'],
            ['id' => 41, 'name' => 'Comoros'],
            ['id' => 42, 'name' => 'Congo'],
            ['id' => 43, 'name' => 'Costa Rica'],
            ['id' => 44, 'name' => 'Croatia'],
            ['id' => 45, 'name' => 'Cuba'],
            ['id' => 46, 'name' => 'Cyprus'],
            ['id' => 47, 'name' => 'Czech Republic'],
            ['id' => 48, 'name' => 'Democratic Republic of Congo'],
            ['id' => 49, 'name' => 'Denmark'],
            ['id' => 50, 'name' => 'Djibouti'],
            ['id' => 51, 'name' => 'Dominica'],
            ['id' => 52, 'name' => 'Dominican Republic'],
            ['id' => 53, 'name' => 'Ecuador'],
            ['id' => 54, 'name' => 'Egypt'],
            ['id' => 55, 'name' => 'El Salvador'],
            ['id' => 56, 'name' => 'Equatorial Guinea'],
            ['id' => 57, 'name' => 'Eritrea'],
            ['id' => 58, 'name' => 'Estonia'],
            ['id' => 59, 'name' => 'Ethiopia'],
            ['id' => 60, 'name' => 'Fiji'],
            ['id' => 61, 'name' => 'Finland'],
            ['id' => 62, 'name' => 'France'],
            ['id' => 63, 'name' => 'French Guiana'],
            ['id' => 64, 'name' => 'Gabon'],
            ['id' => 65, 'name' => 'Gambia'],
            ['id' => 66, 'name' => 'Georgia'],
            ['id' => 67, 'name' => 'Germany'],
            ['id' => 68, 'name' => 'Ghana'],
            ['id' => 69, 'name' => 'Great Britain'],
            ['id' => 70, 'name' => 'Greece'],
            ['id' => 71, 'name' => 'Grenada'],
            ['id' => 72, 'name' => 'Guadeloupe'],
            ['id' => 73, 'name' => 'Guatemala'],
            ['id' => 74, 'name' => 'Guinea'],
            ['id' => 75, 'name' => 'Guinea-Bissau'],
            ['id' => 76, 'name' => 'Guyana'],
            ['id' => 77, 'name' => 'Haiti'],
            ['id' => 78, 'name' => 'Honduras'],
            ['id' => 79, 'name' => 'Hungary'],
            ['id' => 80, 'name' => 'Iceland'],
            ['id' => 81, 'name' => 'India'],
            ['id' => 82, 'name' => 'Indonesia'],
            ['id' => 83, 'name' => 'Iran'],
            ['id' => 84, 'name' => 'Iraq'],
            ['id' => 85, 'name' => 'Israel'],
            ['id' => 86, 'name' => 'Italy'],
            ['id' => 87, 'name' => 'Ivory Coast'],
            ['id' => 88, 'name' => 'Jamaica'],
            ['id' => 89, 'name' => 'Japan'],
            ['id' => 90, 'name' => 'Jordan'],
            ['id' => 91, 'name' => 'Kazakhstan'],
            ['id' => 92, 'name' => 'Kenya'],
            ['id' => 93, 'name' => 'Kosovo'],
            ['id' => 94, 'name' => 'Kuwait'],
            ['id' => 95, 'name' => 'Kyrgyz Republic (Kyrgyzstan)'],
            ['id' => 96, 'name' => 'Laos'],
            ['id' => 97, 'name' => 'Latvia'],
            ['id' => 98, 'name' => 'Lebanon'],
            ['id' => 99, 'name' => 'Lesotho'],
            ['id' => 100, 'name' => 'Liberia'],
            ['id' => 101, 'name' => 'Libya'],
            ['id' => 102, 'name' => 'Liechtenstein'],
            ['id' => 103, 'name' => 'Lithuania'],
            ['id' => 104, 'name' => 'Luxembourg'],
            ['id' => 105, 'name' => 'Macedonia'],
            ['id' => 106, 'name' => 'Madagascar'],
            ['id' => 107, 'name' => 'Malawi'],
            ['id' => 108, 'name' => 'Malaysia'],
            ['id' => 109, 'name' => 'Maldives'],
            ['id' => 110, 'name' => 'Mali'],
            ['id' => 111, 'name' => 'Malta'],
            ['id' => 112, 'name' => 'Martinique'],
            ['id' => 113, 'name' => 'Mauritania'],
            ['id' => 114, 'name' => 'Mauritius'],
            ['id' => 115, 'name' => 'Mayotte'],
            ['id' => 116, 'name' => 'Mexico'],
            ['id' => 117, 'name' => 'Moldova'],
            ['id' => 118, 'name' => 'Monaco'],
            ['id' => 119, 'name' => 'Mongolia'],
            ['id' => 120, 'name' => 'Montenegro'],
            ['id' => 121, 'name' => 'Montserrat'],
            ['id' => 122, 'name' => 'Morocco'],
            ['id' => 123, 'name' => 'Mozambique'],
            ['id' => 124, 'name' => 'Myanmar'],
            ['id' => 125, 'name' => 'Namibia'],
            ['id' => 126, 'name' => 'Nepal'],
            ['id' => 127, 'name' => 'Netherlands'],
            ['id' => 128, 'name' => 'New Zealand'],
            ['id' => 129, 'name' => 'Nicaragua'],
            ['id' => 130, 'name' => 'Niger'],
            ['id' => 131, 'name' => 'Nigeria'],
            ['id' => 132, 'name' => 'North Korea'],
            ['id' => 133, 'name' => 'Norway'],
            ['id' => 134, 'name' => 'Oman'],
            ['id' => 135, 'name' => 'Pacific Islands'],
            ['id' => 136, 'name' => 'Pakistan'],
            ['id' => 137, 'name' => 'Panama'],
            ['id' => 138, 'name' => 'Papua New Guinea'],
            ['id' => 139, 'name' => 'Paraguay'],
            ['id' => 140, 'name' => 'Peru'],
            ['id' => 141, 'name' => 'Philippines'],
            ['id' => 142, 'name' => 'Poland'],
            ['id' => 143, 'name' => 'Portugal'],
            ['id' => 144, 'name' => 'Puerto Rico'],
            ['id' => 145, 'name' => 'Qatar'],
            ['id' => 146, 'name' => 'Reunion'],
            ['id' => 147, 'name' => 'Romania'],
            ['id' => 148, 'name' => 'Russian Federation'],
            ['id' => 149, 'name' => 'Rwanda'],
            ['id' => 150, 'name' => 'Saint Kitts and Nevis'],
            ['id' => 151, 'name' => 'Saint Lucia'],
            ['id' => 152, 'name' => "Saint Vincent's & Grenadines"],
            ['id' => 153, 'name' => 'Samoa'],
            ['id' => 154, 'name' => 'Sao Tome and Principe'],
            ['id' => 155, 'name' => 'Saudi Arabia'],
            ['id' => 156, 'name' => 'Senegal'],
            ['id' => 157, 'name' => 'Serbia'],
            ['id' => 158, 'name' => 'Seychelles'],
            ['id' => 159, 'name' => 'Sierra Leone'],
            ['id' => 160, 'name' => 'Singapore'],
            ['id' => 161, 'name' => 'Slovak Republic (Slovakia)'],
            ['id' => 162, 'name' => 'Slovenia'],
            ['id' => 163, 'name' => 'Solomon Islands'],
            ['id' => 164, 'name' => 'Somalia'],
            ['id' => 165, 'name' => 'South Africa'],
            ['id' => 166, 'name' => 'South Korea'],
            ['id' => 167, 'name' => 'South Sudan'],
            ['id' => 168, 'name' => 'Spain'],
            ['id' => 169, 'name' => 'Sri Lanka'],
            ['id' => 170, 'name' => 'Sudan'],
            ['id' => 171, 'name' => 'Suriname'],
            ['id' => 172, 'name' => 'Swaziland'],
            ['id' => 173, 'name' => 'Sweden'],
            ['id' => 174, 'name' => 'Switzerland'],
            ['id' => 175, 'name' => 'Syria'],
            ['id' => 176, 'name' => 'Tajikistan'],
            ['id' => 177, 'name' => 'Tanzania'],
            ['id' => 178, 'name' => 'Thailand'],
            ['id' => 179, 'name' => 'Timor Leste'],
            ['id' => 180, 'name' => 'Togo'],
            ['id' => 181, 'name' => 'Trinidad & Tobago'],
            ['id' => 182, 'name' => 'Tunisia'],
            ['id' => 183, 'name' => 'Turkey'],
            ['id' => 184, 'name' => 'Turkmenistan'],
            ['id' => 185, 'name' => 'Turks & Caicos Islands'],
            ['id' => 186, 'name' => 'Uganda'],
            ['id' => 187, 'name' => 'Ukraine'],
            ['id' => 188, 'name' => 'United Arab Emirates'],
            ['id' => 189, 'name' => 'United States of America (USA)'],
            ['id' => 190, 'name' => 'Uruguay'],
            ['id' => 191, 'name' => 'Uzbekistan'],
            ['id' => 192, 'name' => 'Venezuela'],
            ['id' => 193, 'name' => 'Vietnam'],
            ['id' => 194, 'name' => 'Virgin Islands (UK)'],
            ['id' => 195, 'name' => 'Virgin Islands (US)'],
            ['id' => 196, 'name' => 'Yemen'],
            ['id' => 197, 'name' => 'Zambia'],
            ['id' => 198, 'name' => 'Zimbabwe'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(['id' => $country['id']], $country);
        }
    }
}
