# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7-fpm

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y python-dev git
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install awsebcli --upgrade
          - eb init "Informed365 API" -r $AWS_DEFAULT_REGION -p $APPLICATION_PLATFORM
          - eb deploy $APPLICATION_ENVIRONMENT